[tool.poetry]
name = "tool-ota-mqtt-ymodem"
version = "0.1.0"
description = "Craner LTE MQTT YMODEM OTA host tool."
authors = ["Craner"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
paho-mqtt = "^1.6.1"
pyserial = "^3.5"
pyYmodem = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
